### ISSUE TITLE
Back-to-back Lift imports result in 415 Unsupported Media Error

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#1061]
1. Create a new project and import a 115MB Lift project on creation
2. Data Clean up | Review Entries, play one of the sound files to ensure it uploaded correctly
3. Export the project
4. Create a new project using the exported project

```
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "UploadLiftFile", controller = "Lift"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] UploadLiftFile(System.String, BackendFramework.Models.FileUpload) on controller BackendFramework.Controllers.LiftController (BackendFramework).
info: Microsoft.AspNetCore.Mvc.StatusCodeResult[1]
      Executing HttpStatusCodeResult, setting HTTP status code 415
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action BackendFramework.Controllers.LiftController.UploadLiftFile (BackendFramework) in 15856.7388ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'BackendFramework.Controllers.LiftController.UploadLiftFile (BackendFramework)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 15866.9232ms 415
```

**Comment by johnthagen** [comment]
`LiftController.UploadLiftFile` has a broad `catch` block around the Lift import steps:

```cs
            catch (Exception)
            {
                return new UnsupportedMediaTypeResult();
            }
```

**Comment by johnthagen** [comment]
Stack trace:

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at BackendFramework.Services.WordRepository.Create(List`1 words) in C:\Users\User\GitHub\TheCombine\Backend\Services\WordRepository.cs:line 98
   at BackendFramework.Services.LiftService.LiftMerger.SaveImportEntries() in C:\Users\User\GitHub\TheCombine\Backend\Services\LiftApiServices.cs:line 535
   at BackendFramework.Controllers.LiftController.UploadLiftFile(String projectId, FileUpload fileUpload) in C:\Users\User\GitHub\TheCombine\Backend\Controllers\LiftController.cs:line 161
```

**Comment by johnthagen** [comment]
Maybe related to #1054

**Comment by johnthagen** [comment]
The seems to be some kind of stateful problem in the backend. The first time the backend is started, the project imports correctly. If you then try to import the exact same file again (no exporting going on) it will fail when you try to create a new project using that same import file.

**Comment by johnthagen** [comment]
It seems to be related to mutating a `List<Word>` during the `foreach` enumeration:

```cs
        public async Task<List<Word>> Create(List<Word> words)
        {
            foreach (var w in words)
            {
                PopulateBlankWordTimes(w);
            }
```

https://stackoverflow.com/questions/604831

**Comment by johnthagen** [comment]
When I step through with the debugger in Rider, the error doesn't surface, indicating there could be some kind of race condition involved.
