### ISSUE TITLE
Console error during `npm run test-frontend -- VernDialog`

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#976]
Three instance of:
```
    console.error
      Material-UI: Unable to set focus to a ListItem whose component has not been rendered.

      at node_modules/@material-ui/core/ListItem/ListItem.js:168:17
      at commitHookEffectListMount (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10345:26)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10401:9)
      at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13295:7)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9972:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:318:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
```

**Comment by johnthagen** [comment]
Subtask of #1119

**Comment by imnasnainaec** [comment]
Once this is done, set up jest to fail if any console errors are thrown.
